# RunPod Configuration for BLIP Image Captioning Worker
# This file optimizes the serverless worker for efficiency

[build]
python_version = "3.10"
cuda_version = "11.8"

[runtime]
# Optimize for serverless workloads
handler = "handler.py"
python_executable = "python3"

# Resource optimization
[runtime.environment]
# PyTorch optimizations
TORCH_CUDNN_V8_API_ENABLED = "1"
CUDA_LAUNCH_BLOCKING = "0"
PYTORCH_CUDA_ALLOC_CONF = "max_split_size_mb:128"

# Memory management
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"

# Model caching
HF_HOME = "/huggingface_cache"
TRANSFORMERS_CACHE = "/huggingface_cache"

[runtime.scaling]
# Optimize scaling for image processing workloads
min_workers = 0
max_workers = 10
scale_up_threshold = 2
scale_down_delay = 300  # 5 minutes

[runtime.resources]
# Recommended resource allocation
gpu_memory_utilization = 0.85
cpu_utilization = 0.7
max_request_size = "50MB"  # For handling multiple images

[runtime.health_check]
# Health check settings
timeout = 30
interval = 60
retries = 3
